In [10]:
import numpy as np
# generate random integer between 1 and 10 of size 2 means 2 values as a list, 
# size param can be a single value or a tuple which is the shape of the array
np.random.randint(1, 10,2)

array([9, 7])

In [11]:
# generate random float between 0 and 1 of size 2,3
print(np.random.rand(2,3))
# generate random float from standard normal distribution of size 2,3
print(np.random.randn(2,3))
# generate random integer between 1 and 10 of size 2,3
print(np.random.randint(1,10, (2,3)))
# generate random choice from a list of size 2,3
print(np.random.choice([1,2,3,4,5], size=(2,3)))
# generate random float between 1 and 10 of size 2,3
print(np.random.uniform(1,10, (2,3)))
# generate random float from normal distribution of size 2,3
print(np.random.normal(0,1, (2,3)))
# generate random float between 0 and 100 of size 5,5
print(np.random.rand(5,5)*100)
# Demonstrate the difference between uniform and randint:

# np.random.uniform() generates continuous random numbers (floating point)
# between specified min and max values
print("\nUniform distribution (continuous values between 1 and 10):")
print(np.random.uniform(1, 10, size=10))

# np.random.randint() generates discrete random integers 
# from min (inclusive) to max (exclusive)
print("\nRandom integers (discrete values from 1 to 10):")
print(np.random.randint(1, 11, size=10))

# Key differences:
# 1. uniform() generates floating point numbers, randint() generates integers
# 2. uniform() can generate ANY value between min and max
# 3. randint() only generates whole numbers
# 4. randint() upper bound is exclusive, so we use 11 to get numbers up to 10

# Visual example of density:
print("\nGenerating 1000 numbers to show distribution:")
uniform_nums = np.random.uniform(1, 10, 1000)
randint_nums = np.random.randint(1, 11, 1000)

print("\nUnique values in uniform (showing first 10):")
print(np.unique(uniform_nums)[:10])
print("\nUnique values in randint:")
print(np.unique(randint_nums))



[[0.10004717 0.96351378 0.18644389]
 [0.15077154 0.24340259 0.4151548 ]]
[[-0.14750501  1.69373902 -1.0953346 ]
 [ 0.39764986 -0.73115365  0.51615977]]
[[4 7 9]
 [3 3 3]]
[[1 2 3]
 [5 4 5]]
[[9.55593153 4.2167099  4.56075566]
 [5.60534172 9.43486353 8.86838159]]
[[-1.14535036  0.66178417  0.95130315]
 [-1.42762153  0.25323807  0.97950237]]
[[1 9 1]
 [9 3 7]]
[[0.82429738 0.15030827 0.51457285]
 [0.63013001 0.19854899 0.80910878]]


In [13]:
# Create a 2x3 array filled with ones
print(np.ones((2,3)))

# Create a 2x3 array filled with zeros 
print(np.zeros((2,3)))

# Create a 2x3 array filled with the value 10
print(np.full((2,3), 10))

# Create a 3x3 identity matrix (diagonal elements are 1, rest are 0)
print(np.eye(3))

# Create an array with values from 0 to 9
print("arange from 0 to 9:")
print(np.arange(1,10))

# Create an array with values from 1 to 9, step by 2
print("\narange from 1 to 9 with step 2:")
print(np.arange(1, 10, 2))

# Create an array with 5 evenly spaced values between 0 and 1
print("\nlinspace with 5 points between 0 and 1:")
print(np.linspace(0, 1, 5))

# Create an array with 4 evenly spaced values between 2 and 10
print("\nlinspace with 4 points between 2 and 10:")
print(np.linspace(2, 10, 4))

# Create arrays from lists and tuples
print("\nCreating arrays from lists and tuples:")
list_array = np.array([1, 2, 3, 4, 5])
print("1D array from list:", list_array)

matrix_array = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array from nested lists:")
print(matrix_array)

tuple_array = np.array((1.0, 2.0, 3.0))
print("\nArray from tuple:", tuple_array)



[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[10 10 10]
 [10 10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arange from 0 to 9:
[1 2 3 4 5 6 7 8 9]

arange from 1 to 9 with step 2:
[1 3 5 7 9]

linspace with 5 points between 0 and 1:
[0.   0.25 0.5  0.75 1.  ]

linspace with 4 points between 2 and 10:
[ 2.          4.66666667  7.33333333 10.        ]

Creating arrays from lists and tuples:
1D array from list: [1 2 3 4 5]

2D array from nested lists:
[[1 2 3]
 [4 5 6]]

Array from tuple: [1. 2. 3.]


In [17]:
# Inspecting NumPy Arrays

# Create a sample array to demonstrate inspection methods
sample_array = np.array([[1, 2, 3], 
                        [4, 5, 6],
                        [7, 8, 9]])

# Get the shape (dimensions) of the array
print("Array shape:", sample_array.shape)  # Returns a tuple of array dimensions
# Output: (3, 3) - indicates 3 rows and 3 columns

# Get the number of dimensions (rank)
print("\nNumber of dimensions:", sample_array.ndim)  # Returns the number of axes
# Output: 2 - indicates a 2D array

# Get the total number of elements
print("\nTotal elements:", sample_array.size)  # Returns total number of elements
# Output: 9 - 3x3 matrix has 9 elements

# Get the data type of array elements
print("\nData type:", sample_array.dtype)  # Returns the type of elements
# Output: int64 (or similar depending on system)

# Get the size in bytes of each element
print("\nElement size in bytes:", sample_array.itemsize)  # Returns bytes per element
# Output: 8 (for 64-bit integers)

# Get the total memory used by array in bytes
print("\nTotal memory used:", sample_array.nbytes)  # Returns total bytes used
# Output: 72 (9 elements * 8 bytes)

# Check if array is contiguous in memory
print("\nIs memory contiguous?", sample_array.flags.c_contiguous)
# Output: True if array is stored in a single contiguous block


# Demonstrate array attributes with a more complex example
complex_array = np.array([[[1, 2], [3, 4]], 
                         [[5, 6], [7, 8]]])
print("\nComplex array shape:", complex_array.shape)  # (2, 2, 2)
print("Complex array dimensions:", complex_array.ndim)  # 3
print("Complex array size:", complex_array.size)  # 8
# The error occurs because NumPy arrays don't have an info() method
# Let's remove that line and show array information in a different way

print("\nArray information:")
print("Shape:", sample_array.shape)
print("Dimensions:", sample_array.ndim) 
print("Size:", sample_array.size)
print("Data type:", sample_array.dtype)
print("Memory layout:", sample_array.flags)


Array shape: (3, 3)

Number of dimensions: 2

Total elements: 9

Data type: int32

Element size in bytes: 4

Total memory used: 36

Is memory contiguous? True

Complex array shape: (2, 2, 2)
Complex array dimensions: 3
Complex array size: 8

Array information:
Shape: (3, 3)
Dimensions: 2
Size: 9
Data type: int32
Memory layout:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [ ]:
#for any function in numpy, you can use np.info(function_name) to view the documentation
np.info(np.array) 

In [27]:
# Copying Arrays
print("Copying Arrays:")
original = np.array([1, 2, 3])
view = original.view()  # Creates a view - changes to original affect view
copy = original.copy()  # Creates a deep copy - independent of original

original[0] = 5
print("\nOriginal:", original)  # [5 2 3]
print("View:", view)      # [5 2 3] - view reflects changes
print("Copy:", copy)      # [1 2 3] - copy remains unchanged

# Sorting Arrays
print("\nSorting Arrays:")
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Original array:", unsorted)
print("Sorted array:", np.sort(unsorted))  # Creates new sorted array
unsorted.sort()  # Sorts array in-place
print("In-place sorted:", unsorted)

# Sort 2D array
array_2d = np.array([[3, 1], [2, 4]])
print("\n2D array sorting:")
print("Original:\n", array_2d)
# axis=1 means sort each row independently
print("Sorted along rows:\n", np.sort(array_2d, axis=1))
# axis=0 means sort each column independently
print("Sorted along columns:\n", np.sort(array_2d, axis=0))

# Reshaping Arrays
print("\nReshaping Arrays:")
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)

# reshape(rows, columns) - total elements must match original array
print("Reshaped to 2x3:\n", arr.reshape(2, 3))  # 2 rows, 3 columns
print("Reshaped to 3x2:\n", arr.reshape(3, 2))  # 3 rows, 2 columns

# Negative dimensions in reshape
print("\nNegative dimensions in reshape:")
# -1 tells NumPy to automatically calculate the dimension
print("Reshape to 2x3 using -1:\n", arr.reshape(-1, 3))  # NumPy calculates rows=2
print("Reshape to 3x2 using -1:\n", arr.reshape(3, -1))  # NumPy calculates cols=2

# Multiple -1 dimensions are not allowed
# arr.reshape(-1, -1) would raise an error

# Flattening arrays
print("\nFlattening arrays:")
print("Using reshape(-1):", arr.reshape(-1))  # Flattens to 1D array
print("Using ravel():", arr.ravel())  # Alternative way to flatten

# Order parameter in reshape
print("\nReshape with different orders:")

# 'C' order (row-major) - default
# Elements are read/written in row-by-row order
# For arr = [1,2,3,4,5,6], C-order reshape to 2x3 gives:
# [[1,2,3],
#  [4,5,6]]
print("C-order (row-major):\n", arr.reshape(2, 3, order='C'))

# 'F' order (column-major) - named after Fortran
# Elements are read/written in column-by-column order
# For arr = [1,2,3,4,5,6], F-order reshape to 2x3 gives:
# [[1,3,5],
#  [2,4,6]]
print("F-order (column-major):\n", arr.reshape(2, 3, order='F'))

# The order parameter affects how the elements are arranged
# This is particularly important when:
# 1. Working with data from different programming languages
# 2. Optimizing memory access patterns
# 3. Interfacing with libraries that expect specific memory layouts

# Transposing Arrays
print("\nTransposing Arrays:")
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", arr)

# Transpose the array
print("\nTransposed array:\n", arr.T)

# Transpose with reshape
print("\nTransposed with reshape:\n", arr.reshape(3, 2).T)

# Difference between resize and reshape
print("\nDifference between resize and reshape:")

# Create a sample array
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# reshape vs resize
print("\n1. Shape compatibility:")
# reshape requires total size to remain same
print("reshape(2,3) will fail:", "Error - cannot reshape (5,) to (2,3)")

# resize can change total size
arr.resize((2,3), refcheck=False)  # refcheck=False needed in Jupyter
print("resize(2,3) works:\n", arr)  # Extra elements filled with zeros

# Create new array for reshape example
arr = np.array([1, 2, 3, 4, 5, 6])
print("\nNew array:", arr)

print("\n2. Return behavior:")
# reshape returns new array, original unchanged
reshaped = arr.reshape(2,3)
print("After reshape - original:", arr)
print("Reshaped array:\n", reshaped)

# resize modifies array in-place
arr.resize((2,3), refcheck=False)
print("\nAfter resize - original modified:\n", arr)

print("\n3. Memory handling:")
arr = np.array([1, 2, 3, 4])
print("\nStarting array:", arr)

# reshape must preserve exact size
print("reshape must keep same total size:", arr.reshape(2,2))  # Only works if size matches

# resize can make array smaller
arr.resize((3,), refcheck=False)
print("resize to smaller:", arr)  # Truncates elements

# resize can make array larger
arr.resize((6,), refcheck=False)
print("resize to larger:", arr)  # New elements are 0



Copying Arrays:

Original: [5 2 3]
View: [5 2 3]
Copy: [1 2 3]

Sorting Arrays:
Original array: [3 1 4 1 5 9 2 6]
Sorted array: [1 1 2 3 4 5 6 9]
In-place sorted: [1 1 2 3 4 5 6 9]

2D array sorting:
Original:
 [[3 1]
 [2 4]]
Sorted along rows:
 [[1 3]
 [2 4]]
Sorted along columns:
 [[2 1]
 [3 4]]

Reshaping Arrays:
Original array: [1 2 3 4 5 6]
Reshaped to 2x3:
 [[1 2 3]
 [4 5 6]]
Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Negative dimensions in reshape:
Reshape to 2x3 using -1:
 [[1 2 3]
 [4 5 6]]
Reshape to 3x2 using -1:
 [[1 2]
 [3 4]
 [5 6]]

Flattening arrays:
Using reshape(-1): [1 2 3 4 5 6]
Using ravel(): [1 2 3 4 5 6]

Reshape with different orders:
C-order (row-major):
 [[1 2 3]
 [4 5 6]]
F-order (column-major):
 [[1 3 5]
 [2 4 6]]

Transposing Arrays:
Original array:
 [[1 2 3]
 [4 5 6]]

Transposed array:
 [[1 4]
 [2 5]
 [3 6]]

Transposed with reshape:
 [[1 3 5]
 [2 4 6]]

Difference between resize and reshape:
Original array: [1 2 3 4 5]

1. Shape compatibility:
reshape(2,3)

In [31]:
print("\nAdding and Removing Elements:")

# Create sample array
arr = np.array([1, 2, 3, 4])
print("Original array:", arr)

# append - adds elements to end
arr_append = np.append(arr, [5, 6])
print("\nAfter append:", arr_append)

# insert - adds element at specific position
arr_insert = np.insert(arr, 1, 5)  # insert 5 at index 1
print("After insert:", arr_insert)

# delete - removes element at specific position
arr_delete = np.delete(arr, 1)  # delete element at index 1
print("After delete:", arr_delete)

# concatenate - join arrays
arr2 = np.array([5, 6, 7])
arr_concat = np.concatenate((arr, arr2))
print("\nConcatenated arrays:", arr_concat)

# stack arrays
arr3 = np.array([8, 9, 10, 11])
# vertical stack
arr_vstack = np.vstack((arr, arr3))
print("\nVertical stack:\n", arr_vstack)

# horizontal stack
arr_hstack = np.hstack((arr, arr3))
print("\nHorizontal stack:", arr_hstack)


print("\n2D Array Operations:")

# Create sample 2D arrays
arr_2d = np.array([[1, 2], [3, 4]])
print("Original 2D array:\n", arr_2d)

# append - adds row or column to 2D array
arr_2d_append = np.append(arr_2d, [[5, 6]], axis=0)  # Add new row
print("\nAfter appending row:\n", arr_2d_append)

# insert - adds row/column at specific position
arr_2d_insert = np.insert(arr_2d, 1, [5, 6], axis=0)  # Insert row at index 1
print("\nAfter inserting row at position 1:\n", arr_2d_insert)

# delete - removes row/column at specific position
arr_2d_delete = np.delete(arr_2d, 1, axis=0)  # Delete row at index 1
print("\nAfter deleting row at position 1:\n", arr_2d_delete)




Adding and Removing Elements:
Original array: [1 2 3 4]

After append: [1 2 3 4 5 6]
After insert: [1 5 2 3 4]
After delete: [1 3 4]

Concatenated arrays: [1 2 3 4 5 6 7]

Vertical stack:
 [[ 1  2  3  4]
 [ 8  9 10 11]]

Horizontal stack: [ 1  2  3  4  8  9 10 11]

2D Array Operations:
Original 2D array:
 [[1 2]
 [3 4]]

After appending row:
 [[1 2]
 [3 4]
 [5 6]]

After inserting row at position 1:
 [[1 2]
 [5 6]
 [3 4]]

After deleting row at position 1:
 [[1 2]]


In [32]:
# Create another 2D array for joining
arr_2d_2 = np.array([[5, 6], [7, 8]])
print("\nSecond 2D array:\n", arr_2d_2)

# concatenate - join 2D arrays
arr_2d_concat = np.concatenate((arr_2d, arr_2d_2), axis=0)  # Join vertically
print("\nConcatenated arrays vertically:\n", arr_2d_concat)

# Create third 2D array for stacking
arr_2d_3 = np.array([[9, 10], [11, 12]])
print("\nThird 2D array:\n", arr_2d_3)

# vertical stack - stack arrays vertically
arr_2d_vstack = np.vstack((arr_2d, arr_2d_3))
print("\nVertical stack:\n", arr_2d_vstack)

# horizontal stack - stack arrays horizontally 
arr_2d_hstack = np.hstack((arr_2d, arr_2d_3))
print("\nHorizontal stack:\n", arr_2d_hstack)


Second 2D array:
 [[5 6]
 [7 8]]

Concatenated arrays vertically:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Third 2D array:
 [[ 9 10]
 [11 12]]

Vertical stack:
 [[ 1  2]
 [ 3  4]
 [ 9 10]
 [11 12]]

Horizontal stack:
 [[ 1  2  9 10]
 [ 3  4 11 12]]


In [36]:
print("\nSplitting Arrays:")

# Create a sample array
arr_split = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr_split)

# Split array into 3 equal parts if it can not be divided evenly, it will raise an error
split_arr = np.split(arr_split, 3)
print("\nSplit into 3 equal parts:", split_arr)

# Split array at specific indices
split_arr_2 = np.array_split(arr_split, [2, 4])
print("\nSplit at indices [2, 4]:", split_arr_2)

print("\nSplitting 2D Arrays:")

# Create a sample 2D array
arr_2d_split = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print("Original 2D array:\n", arr_2d_split)

# Split 2D array horizontally (row-wise)
split_2d_h = np.hsplit(arr_2d_split, 3)  # Split into 3 columns
print("\nHorizontal split (by columns):")
for i, arr in enumerate(split_2d_h):
    print(f"Split {i+1}:\n", arr)

# Split 2D array vertically (column-wise)
# we can give the indices of the rows to split the array or we can give the number of rows to split the array
split_2d_v = np.vsplit(arr_2d_split, [1,3])  # Split into 2 rows
print("\nVertical split (by rows):")
for i, arr in enumerate(split_2d_v):
    print(f"Split {i+1}:\n", arr)

#here we can see that hsplit is splitting the array in column wise and vsplit is splitting the array in row wise where names are opposite of each other



Splitting Arrays:
Original array: [1 2 3 4 5 6]

Split into 3 equal parts: [array([1, 2]), array([3, 4]), array([5, 6])]

Split at indices [2, 4]: [array([1, 2]), array([3, 4]), array([5, 6])]

Splitting 2D Arrays:
Original 2D array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Horizontal split (by columns):
Split 1:
 [[ 1]
 [ 4]
 [ 7]
 [10]]
Split 2:
 [[ 2]
 [ 5]
 [ 8]
 [11]]
Split 3:
 [[ 3]
 [ 6]
 [ 9]
 [12]]

Vertical split (by rows):
Split 1:
 [[1 2 3]]
Split 2:
 [[4 5 6]
 [7 8 9]]
Split 3:
 [[10 11 12]]


In [37]:
print("\nIndexing, Slicing and Subsetting in NumPy:")

# Create a sample array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Indexing - accessing single elements
print("\nIndexing:")
print("First element:", arr[0])
print("Last element:", arr[-1])

# Slicing - accessing a range of elements
print("\nSlicing:")
print("Elements from index 2 to 5:", arr[2:6])  # Note: end index is exclusive
print("Elements from start to index 4:", arr[:5])
print("Elements from index 6 to end:", arr[6:])
print("Every second element:", arr[::2])
print("Reverse array:", arr[::-1])

# Create a 2D array for demonstration
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("\nOriginal 2D array:\n", arr_2d)

# Indexing in 2D arrays
print("\n2D array indexing:")
print("Element at row 1, column 2:", arr_2d[1, 2])  # Same as arr_2d[1][2]

# Slicing in 2D arrays
print("\n2D array slicing:")
print("First two rows, all columns:\n", arr_2d[:2, :])
print("\nAll rows, last two columns:\n", arr_2d[:, 2:])
print("\nSubset (rows 1-2, columns 1-2):\n", arr_2d[1:3, 1:3])

# Boolean indexing
print("\nBoolean indexing:")
bool_idx = arr > 5
print("Elements greater than 5:", arr[bool_idx])
# Alternative way
print("Elements greater than 5 (alternative):", arr[arr > 5])

# Fancy indexing
print("\nFancy indexing:")
indices = [1, 3, 5]
print("Elements at indices 1, 3, and 5:", arr[indices])



Indexing, Slicing and Subsetting in NumPy:
Original array: [ 1  2  3  4  5  6  7  8  9 10]

Indexing:
First element: 1
Last element: 10

Slicing:
Elements from index 2 to 5: [3 4 5 6]
Elements from start to index 4: [1 2 3 4 5]
Elements from index 6 to end: [ 7  8  9 10]
Every second element: [1 3 5 7 9]
Reverse array: [10  9  8  7  6  5  4  3  2  1]

Original 2D array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

2D array indexing:
Element at row 1, column 2: 7

2D array slicing:
First two rows, all columns:
 [[1 2 3 4]
 [5 6 7 8]]

All rows, last two columns:
 [[ 3  4]
 [ 7  8]
 [11 12]]

Subset (rows 1-2, columns 1-2):
 [[ 6  7]
 [10 11]]

Boolean indexing:
Elements greater than 5: [ 6  7  8  9 10]
Elements greater than 5 (alternative): [ 6  7  8  9 10]

Fancy indexing:
Elements at indices 1, 3, and 5: [2 4 6]


In [38]:
# Scalar math operations
print("\nScalar math operations:")
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# Addition
print("Add 2 to each element:", arr + 2)

# Subtraction 
print("Subtract 1 from each element:", arr - 1)

# Multiplication
print("Multiply each element by 3:", arr * 3)

# Division
print("Divide each element by 2:", arr / 2)

# Power
print("Square each element:", arr ** 2)

# Multiple operations
print("Complex operation (2x + 1):", 2 * arr + 1)

# Universal functions (ufuncs)
print("\nUniversal functions:")
print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Natural log:", np.log(arr))



Scalar math operations:
Original array: [1 2 3 4 5]
Add 2 to each element: [3 4 5 6 7]
Subtract 1 from each element: [0 1 2 3 4]
Multiply each element by 3: [ 3  6  9 12 15]
Divide each element by 2: [0.5 1.  1.5 2.  2.5]
Square each element: [ 1  4  9 16 25]
Complex operation (2x + 1): [ 3  5  7  9 11]

Universal functions:
Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural log: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [41]:
# Vector math operations
print("\nVector math operations:")
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 4, 5, 6])
print("Array 1:", arr1)
print("Array 2:", arr2)

# Element-wise addition
print("Element-wise addition:", arr1 + arr2)

# Element-wise subtraction
print("Element-wise subtraction:", arr1 - arr2)

# Element-wise multiplication
print("Element-wise multiplication:", arr1 * arr2)

# Element-wise division
print("Element-wise division:", arr1 / arr2)

# Trigonometric functions
print("\nTrigonometric functions:")
print("Sine:", np.sin(arr1))
print("Cosine:", np.cos(arr1))
print("Tangent:", np.tan(arr1))

# Inverse trigonometric functions 
print("\nInverse trigonometric functions:")
print("Arcsin:", np.arcsin(arr1/10))  # Using arr1/10 to ensure values are in [-1,1]
print("Arccos:", np.arccos(arr1/10))
print("Arctan:", np.arctan(arr1))



# Dot product
print("Dot product:", np.dot(arr1, arr2))

# Vector norm (magnitude)
print("Magnitude of arr1:", np.linalg.norm(arr1))
print("Magnitude of arr2:", np.linalg.norm(arr2))

# Vector comparison
print("\nVector comparison:")
print("Element-wise greater than:", arr1 > arr2)
print("Element-wise equal:", arr1 == arr2)
print("Arrays are equal:", np.array_equal(arr1, arr2))



Vector math operations:
Array 1: [1 2 3 4 5]
Array 2: [2 3 4 5 6]
Element-wise addition: [ 3  5  7  9 11]
Element-wise subtraction: [-1 -1 -1 -1 -1]
Element-wise multiplication: [ 2  6 12 20 30]
Element-wise division: [0.5        0.66666667 0.75       0.8        0.83333333]

Trigonometric functions:
Sine: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine: [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Tangent: [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]

Inverse trigonometric functions:
Arcsin: [0.10016742 0.20135792 0.30469265 0.41151685 0.52359878]
Arccos: [1.47062891 1.36943841 1.26610367 1.15927948 1.04719755]
Arctan: [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077]
Dot product: 70
Magnitude of arr1: 7.416198487095663
Magnitude of arr2: 9.486832980505138

Vector comparison:
Element-wise greater than: [False False False False False]
Element-wise equal: [False False False False False]
Arrays are equal: False


In [42]:
# Statistical functions
print("\nStatistical functions:")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Array:", arr)

# Basic statistics
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard deviation:", np.std(arr))
print("Variance:", np.var(arr))

# Min/Max
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Range:", np.ptp(arr))  # Peak to peak (max - min)

# Percentiles
print("25th percentile:", np.percentile(arr, 25))
print("50th percentile:", np.percentile(arr, 50))  # Same as median
print("75th percentile:", np.percentile(arr, 75))

# Additional statistics
print("Sum:", np.sum(arr))
print("Cumulative sum:", np.cumsum(arr))
print("Product:", np.prod(arr))
print("Cumulative product:", np.cumprod(arr))



Statistical functions:
Array: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25
Minimum: 1
Maximum: 10
Range: 9
25th percentile: 3.25
50th percentile: 5.5
75th percentile: 7.75
Sum: 55
Cumulative sum: [ 1  3  6 10 15 21 28 36 45 55]
Product: 3628800
Cumulative product: [      1       2       6      24     120     720    5040   40320  362880
 3628800]


In [46]:
#saving and loading numpy arrays

#saving numpy array to a file
np.save('my_array.npy', arr)

#loading numpy array from a file
arr = np.load('my_array.npy')

#saving multiple arrays to a file
np.savez('my_arrays.npz', arr1=arr1, arr2=arr2)

#loading multiple arrays from a file
data = np.load('my_arrays.npz')
arr1 = data['arr1']
arr2 = data['arr2']

#saving arrays in text format
np.savetxt('my_array.txt', arr) #default delimiter is space

#loading text file
arr = np.loadtxt('my_array.txt')
print("Array loaded from text file:", arr)

#saving arrays in binary format
np.save('my_array.npy', arr)

#loading binary file
arr = np.load('my_array.npy')
print("Array loaded from binary file:", arr)

#saving arrays in csv format
np.savetxt('my_array.csv', arr, delimiter=',')

#loading csv file
arr = np.loadtxt('my_array.csv', delimiter=',')
print("Array loaded from CSV file:", arr)

#saving arrays in json format
np.save('my_array.json.npy', arr)

#loading json file
arr = np.load('my_array.json.npy')
print("Array loaded from JSON file:", arr)







Array loaded from text file: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Array loaded from binary file: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Array loaded from CSV file: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Array loaded from JSON file: [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
https://www.kaggle.com/code/muhammadanasmahmood/python-numpy-in-practice-basic-to-advanced/notebook