In [49]:
import pandas as pd
import numpy as np

In [50]:
# we can use Series to handle one-dimensional Data
# params : data and index
print(pd.Series([1,2,3,4],index= [4,5,6,7]))

# for index we can pass the iterable 

print(pd.Series(np.arange(0,10)))
print(pd.Series(np.arange(0,10),index = range(2,12)))

4    1
5    2
6    3
7    4
dtype: int64
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32
2     0
3     1
4     2
5     3
6     4
7     5
8     6
9     7
10    8
11    9
dtype: int32


In [51]:
s = pd.Series(np.arange(0,10),index = range(2,12))
s.dtype
s.array
# s.at[5]
# s.to_numpy()


<NumpyExtensionArray>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Length: 10, dtype: int32

In [52]:
d = {"a": 0.0, "b": 1.0, "c": 2.0}

pd.Series(d)

#series can be accessed as dict
print(d['a'])

0.0


In [53]:
# Series can be accessed as a ndarray
print(s[3:7])
print(np.exp(s))
print(s[s > s.median()])


5    3
6    4
7    5
8    6
dtype: int32
2        1.000000
3        2.718282
4        7.389056
5       20.085537
6       54.598150
7      148.413159
8      403.428793
9     1096.633158
10    2980.957987
11    8103.083928
dtype: float64
7     5
8     6
9     7
10    8
11    9
dtype: int32


# DataFrame

In [54]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

df = pd.DataFrame(d)
df['three'] = df["one"] + df["two"]
df

# DataFrame is not intended to work exactly like a 2-dimensional NumPy ndarray.


one  two  three
a  1.0  1.0    2.0
b  2.0  2.0    4.0
c  3.0  3.0    6.0
d  NaN  4.0    NaN

In [55]:
#delete the column
df = df.drop('three', axis=1)
print(df)

#delete the row
df = df.drop('a', axis=0)
print(df)


   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0
   one  two
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0


In [56]:
# for inserting a scalar value to the DataFrame,it will propagate the value to all the elements in the DataFrame
# assign() always returns a copy of the data, leaving the original DataFrame untouched.

df = df.assign(three = 3.0)
print(df)

# for inserting a scalar value to the DataFrame,it will propagate the value to all the elements in the DataFrame
df["four"] = "Four"
print(df)

# if you dont have the values for all the index,it will fill the missing values with NaN
df["five"] = df["two"][:2]
print(df)

# if you dont have the values for all the index,it will fill the missing values with NaN
df["five"] = df["two"][[1,2]]
print(df)



   one  two  three
b  2.0  2.0    3.0
c  3.0  3.0    3.0
d  NaN  4.0    3.0
   one  two  three  four
b  2.0  2.0    3.0  Four
c  3.0  3.0    3.0  Four
d  NaN  4.0    3.0  Four
   one  two  three  four  five
b  2.0  2.0    3.0  Four   2.0
c  3.0  3.0    3.0  Four   3.0
d  NaN  4.0    3.0  Four   NaN
   one  two  three  four  five
b  2.0  2.0    3.0  Four   NaN
c  3.0  3.0    3.0  Four   3.0
d  NaN  4.0    3.0  Four   4.0


C:\Users\IsmartSiva\AppData\Local\Temp\ipykernel_22092\1696057931.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df["five"] = df["two"][[1,2]]


# Indexing / selection
| Operation | Syntax | Result |
|-----------|--------|--------|
| Select column | df[col] | Series |
| Select row by label | df.loc[label] | Series |
| Select row by integer location | df.iloc[loc] | Series |
| Slice rows | df[5:10] | DataFrame |
| Select rows by boolean vector | df[bool_vec] | DataFrame |


In [57]:
df = pd.DataFrame(np.random.randn(10, 4), columns=["A", "B", "C", "D"])
df2 = pd.DataFrame(np.random.randn(7, 3), columns=["A", "B", "C"])
df+df2

A         B         C   D
0 -2.132261  0.903886  0.794457 NaN
1  0.143645 -3.000754 -2.054936 NaN
2  2.181318  0.316150  0.818822 NaN
3 -0.718930  0.521114 -0.172140 NaN
4 -0.191914 -0.809036  1.661117 NaN
5 -0.347272  1.064155  1.012747 NaN
6  1.873125  2.238738 -2.152600 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN

In [58]:
# for creating a DataFrame with dates a
dates = pd.date_range("20131231",periods=6)
dates

DatetimeIndex(['2013-12-31', '2014-01-01', '2014-01-02', '2014-01-03',
               '2014-01-04', '2014-01-05'],
              dtype='datetime64[ns]', freq='D')

In [59]:
df = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.date_range("20130102",periods=10),
        "C": pd.Series(1,index=list(range(10)),dtype="float32"),
        "D": np.array([3] * 10,dtype="int32"),
        "E": pd.Categorical(["test","train","test","train","test","train","test","train","test","train"]),
        "F": "foo",
    }
)
df

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-03  1.0  3  train  foo
2  1.0 2013-01-04  1.0  3   test  foo
3  1.0 2013-01-05  1.0  3  train  foo
4  1.0 2013-01-06  1.0  3   test  foo
5  1.0 2013-01-07  1.0  3  train  foo
6  1.0 2013-01-08  1.0  3   test  foo
7  1.0 2013-01-09  1.0  3  train  foo
8  1.0 2013-01-10  1.0  3   test  foo
9  1.0 2013-01-11  1.0  3  train  foo

In [60]:
# to get the first 5 rows
print(df.head())
# to get the last 5 rows
print(df.tail())
# to get the number of rows and columns
print(df.shape)
# to get the index
print(df.index)
# to get the columns
print(df.columns)
# to get the values
print(df.values)


     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-03  1.0  3  train  foo
2  1.0 2013-01-04  1.0  3   test  foo
3  1.0 2013-01-05  1.0  3  train  foo
4  1.0 2013-01-06  1.0  3   test  foo
     A          B    C  D      E    F
5  1.0 2013-01-07  1.0  3  train  foo
6  1.0 2013-01-08  1.0  3   test  foo
7  1.0 2013-01-09  1.0  3  train  foo
8  1.0 2013-01-10  1.0  3   test  foo
9  1.0 2013-01-11  1.0  3  train  foo
(10, 6)
Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-03 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-04 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-05 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-06 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-07 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-08 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timesta

In [61]:
df = pd.DataFrame(np.random.rand(6, 4)*10, index=dates, columns=list("ABCD"))

df

A         B         C         D
2013-12-31  7.188154  2.257619  9.011891  8.475116
2014-01-01  0.689308  1.978226  9.593426  0.455551
2014-01-02  3.634282  5.664518  2.939398  2.836616
2014-01-03  4.582159  4.676392  1.618480  1.870843
2014-01-04  4.878874  9.050554  7.168809  2.550571
2014-01-05  8.196116  5.235925  2.307923  2.001258

In [62]:
# for converting the DataFrame to a numpy array
print(df.to_numpy())

# for converting the DataFrame to a csv file
# df.to_csv("df.csv",index=False)

# describe for summary of the DataFrame
print(df.describe())

# for getting the mean of the DataFrame
print(df.mean())




[[7.18815429 2.25761897 9.01189087 8.47511633]
 [0.68930835 1.97822583 9.5934256  0.45555099]
 [3.63428167 5.66451809 2.9393977  2.83661619]
 [4.58215867 4.67639157 1.61847965 1.87084262]
 [4.87887411 9.0505539  7.16880941 2.55057119]
 [8.19611562 5.23592521 2.30792271 2.00125822]]
              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   4.861482  4.810539  5.439988  3.031659
std    2.665504  2.586324  3.568335  2.790923
min    0.689308  1.978226  1.618480  0.455551
25%    3.871251  2.862312  2.465791  1.903447
50%    4.730516  4.956158  5.054104  2.275915
75%    6.610834  5.557370  8.551121  2.765105
max    8.196116  9.050554  9.593426  8.475116
A    4.861482
B    4.810539
C    5.439988
D    3.031659
dtype: float64


In [63]:
## Sorting 

# sort_index() sorts the DataFrame by index
# axis=1 means sort by columns (axis=0 would sort by row index)
# ascending=False means sort in descending order (Z to A)
# In this case, it sorts the columns D,C,B,A instead of A,B,C,D
print(df)
print(df.sort_index(axis=1, ascending=False))
# sorting means sort by rows
print(df.sort_index(axis=0, ascending=False))

# sort by column 
print(df.sort_values(by="B", ascending=False))


                   A         B         C         D
2013-12-31  7.188154  2.257619  9.011891  8.475116
2014-01-01  0.689308  1.978226  9.593426  0.455551
2014-01-02  3.634282  5.664518  2.939398  2.836616
2014-01-03  4.582159  4.676392  1.618480  1.870843
2014-01-04  4.878874  9.050554  7.168809  2.550571
2014-01-05  8.196116  5.235925  2.307923  2.001258
                   D         C         B         A
2013-12-31  8.475116  9.011891  2.257619  7.188154
2014-01-01  0.455551  9.593426  1.978226  0.689308
2014-01-02  2.836616  2.939398  5.664518  3.634282
2014-01-03  1.870843  1.618480  4.676392  4.582159
2014-01-04  2.550571  7.168809  9.050554  4.878874
2014-01-05  2.001258  2.307923  5.235925  8.196116
                   A         B         C         D
2014-01-05  8.196116  5.235925  2.307923  2.001258
2014-01-04  4.878874  9.050554  7.168809  2.550571
2014-01-03  4.582159  4.676392  1.618480  1.870843
2014-01-02  3.634282  5.664518  2.939398  2.836616
2014-01-01  0.689308  1.978226 

In [64]:
# loc is for accesing the row data
df.loc[[dates[0],dates[1]],['A','B']]

# using at function for getting Values
df.at[dates[0], "A"]

#  uinsg iloc function

print(df.iloc[2:,1:2])

print(df.iloc[3])

print(df.iloc[[1, 2, 4], [0, 2]])

# For getting fast access to a scalar
print(df.iat[1,1])






                   B
2014-01-02  5.664518
2014-01-03  4.676392
2014-01-04  9.050554
2014-01-05  5.235925
A    4.582159
B    4.676392
C    1.618480
D    1.870843
Name: 2014-01-03 00:00:00, dtype: float64
                   A         C
2014-01-01  0.689308  9.593426
2014-01-02  3.634282  2.939398
2014-01-04  4.878874  7.168809
1.978225825307166


In [65]:
#Boolean Indexing

print(df[df['A'] > 0])

print(df[df['A'] > 0][['B','C']])

df["E"] = ["one", "one", "two", "three", "four", "three"]

# isin() is for checking if the values are in the list
print(df[df["E"].isin(["two", "four"])])







                   A         B         C         D
2013-12-31  7.188154  2.257619  9.011891  8.475116
2014-01-01  0.689308  1.978226  9.593426  0.455551
2014-01-02  3.634282  5.664518  2.939398  2.836616
2014-01-03  4.582159  4.676392  1.618480  1.870843
2014-01-04  4.878874  9.050554  7.168809  2.550571
2014-01-05  8.196116  5.235925  2.307923  2.001258
                   B         C
2013-12-31  2.257619  9.011891
2014-01-01  1.978226  9.593426
2014-01-02  5.664518  2.939398
2014-01-03  4.676392  1.618480
2014-01-04  9.050554  7.168809
2014-01-05  5.235925  2.307923
                   A         B         C         D     E
2014-01-02  3.634282  5.664518  2.939398  2.836616   two
2014-01-04  4.878874  9.050554  7.168809  2.550571  four


# Missing data

In [66]:
# df.pop("E")
# print(df)



df1 = df.reindex(index=dates[0:4], columns=list(df.columns)+["E"])
df1.loc[dates[0]:dates[1], "E"] = 1

# dropna() is for dropping the missing values how can be any or all
# df1.dropna(how="any",inplace=True)
df1.dropna(how="any")

print(df1.isna().sum())
print(df1)
# fillna() is for filling the missing values inplace is for changing the original dataframe
df1.fillna(value=5,inplace=True)
print(df1)








A    0
B    0
C    0
D    0
E    0
E    0
dtype: int64
                   A         B         C         D      E      E
2013-12-31  7.188154  2.257619  9.011891  8.475116      1      1
2014-01-01  0.689308  1.978226  9.593426  0.455551      1      1
2014-01-02  3.634282  5.664518  2.939398  2.836616    two    two
2014-01-03  4.582159  4.676392  1.618480  1.870843  three  three
                   A         B         C         D      E      E
2013-12-31  7.188154  2.257619  9.011891  8.475116      1      1
2014-01-01  0.689308  1.978226  9.593426  0.455551      1      1
2014-01-02  3.634282  5.664518  2.939398  2.836616    two    two
2014-01-03  4.582159  4.676392  1.618480  1.870843  three  three


In [67]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)
print(s)
print(df)

df.pop('E')
# sub is for subtracting the series from the dataframe
print(df.sub(s, axis="index"))

# mean is for getting the mean of the dataframe
print(df.mean(axis = 0))

2013-12-31    NaN
2014-01-01    NaN
2014-01-02    1.0
2014-01-03    3.0
2014-01-04    5.0
2014-01-05    NaN
Freq: D, dtype: float64
                   A         B         C         D      E
2013-12-31  7.188154  2.257619  9.011891  8.475116    one
2014-01-01  0.689308  1.978226  9.593426  0.455551    one
2014-01-02  3.634282  5.664518  2.939398  2.836616    two
2014-01-03  4.582159  4.676392  1.618480  1.870843  three
2014-01-04  4.878874  9.050554  7.168809  2.550571   four
2014-01-05  8.196116  5.235925  2.307923  2.001258  three
                   A         B         C         D
2013-12-31       NaN       NaN       NaN       NaN
2014-01-01       NaN       NaN       NaN       NaN
2014-01-02  2.634282  4.664518  1.939398  1.836616
2014-01-03  1.582159  1.676392 -1.381520 -1.129157
2014-01-04 -0.121126  4.050554  2.168809 -2.449429
2014-01-05       NaN       NaN       NaN       NaN
A    4.861482
B    4.810539
C    5.439988
D    3.031659
dtype: float64


In [68]:
# user defined function
print(df.transform(lambda x: x * 101.2))
print(df.agg(lambda x: np.mean(x) * 5.6))

                     A           B           C           D
2013-12-31  727.441214  228.471040  912.003356  857.681773
2014-01-01   69.758005  200.196454  970.854671   46.101760
2014-01-02  367.789305  573.249230  297.467047  287.065559
2014-01-03  463.714457  473.250826  163.790140  189.329273
2014-01-04  493.742060  915.916054  725.483513  258.117804
2014-01-05  829.446901  529.875632  233.561778  202.527331
A    27.224300
B    26.939018
C    30.463931
D    16.977292
dtype: float64


In [69]:
df.iloc[1:,2:]
df[:3]


A         B         C         D
2013-12-31  7.188154  2.257619  9.011891  8.475116
2014-01-01  0.689308  1.978226  9.593426  0.455551
2014-01-02  3.634282  5.664518  2.939398  2.836616

# Merging


In [70]:
df = pd.DataFrame(np.random.randn(10, 4))
print(df)
pieces = [df[:3], df[3:7], df[7:]]
# Concatenating pandas objects together row-wise with concat()
pd.concat(pieces)

# Concatenating pandas objects together column-wise with concat()
# The pieces have different row counts (3, 4, and 3 rows) so concat preserves all rows
# To get only 3 rows, we need to specify inner join
print(pd.concat(pieces, axis=1)) 

print(df[3:7])


          0         1         2         3
0 -2.482880  0.414765 -0.827761  1.667302
1 -0.992924 -0.182241  1.673199 -0.864833
2 -0.894216  1.309580 -0.021403  0.064083
3  1.075556  0.085793  0.909285 -0.468489
4  0.139474  0.139487  0.779801 -1.203418
5  1.205909 -2.019845  0.954524  0.503120
6  0.938164 -0.697601  1.666527  0.768839
7  0.792405 -0.936001  0.565610  1.259301
8  1.365384  1.526153  0.069581  0.279934
9 -1.543852  0.376203  0.928010  0.651361
          0         1         2         3         0         1         2  \
0 -2.482880  0.414765 -0.827761  1.667302       NaN       NaN       NaN   
1 -0.992924 -0.182241  1.673199 -0.864833       NaN       NaN       NaN   
2 -0.894216  1.309580 -0.021403  0.064083       NaN       NaN       NaN   
3       NaN       NaN       NaN       NaN  1.075556  0.085793  0.909285   
4       NaN       NaN       NaN       NaN  0.139474  0.139487  0.779801   
5       NaN       NaN       NaN       NaN  1.205909 -2.019845  0.954524   
6       NaN  

In [71]:
# merge() enables SQL style join types along specific columns

left = pd.DataFrame({'key': ['foo', 'bar'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [3, 4]})

print(pd.merge(left, right, on='key'))


   key  lval  rval
0  foo     1     3
1  bar     2     4


# Grouping

In [72]:
df = pd.DataFrame(
    {
        "A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
        "B": ["one", "one", "two", "three", "two", "two", "one", "three"],
        "C": np.random.randn(8),
        "D": np.random.randn(8),
    }
)
print(df)
print(df.groupby("A")[["C", "D"]].sum())
print(df.groupby(["A", "B"])[["D"]].sum())


     A      B         C         D
0  foo    one  0.246559  0.395539
1  bar    one -1.241743  0.889199
2  foo    two  1.043200 -0.675227
3  bar  three  1.837874  0.867148
4  foo    two  0.281615  0.945538
5  bar    two -0.405323 -0.021608
6  foo    one -1.019528 -0.322238
7  foo  three -0.103069 -0.076780
            C         D
A                      
bar  0.190808  1.734739
foo  0.448777  0.266831
                  D
A   B              
bar one    0.889199
    three  0.867148
    two   -0.021608
foo one    0.073301
    three -0.076780
    two    0.270311


# Reshaping


In [74]:
arrays = [
   ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
   ["one", "two", "one", "two", "one", "two", "one", "two"],
]
df = pd.DataFrame(
    [["bar", "one"], ["bar", "two"], ["foo", "one"], ["foo", "two"]],
    columns=["first", "second"],
)
df

first second
0   bar    one
1   bar    two
2   foo    one
3   foo    two

In [75]:
# Stacking 
stacked = df2.stack(future_stack=True)
stacked

0  A   -1.671975
   B    0.382662
   C    0.467773
1  A    0.245889
   B   -0.934411
   C   -1.392230
2  A    1.033230
   B    0.204103
   C    0.394591
3  A   -0.231693
   B   -0.003922
   C   -1.049796
4  A    0.625616
   B   -0.550391
   C    1.109820
5  A   -0.544241
   B    0.376626
   C    1.484478
6  A    0.328960
   B    1.928061
   C   -0.646770
dtype: float64

In [78]:
df = pd.DataFrame(
    {"AAA": [4, 5, 6, 7], "BBB": [10, 20, 30, 40], "CCC": [100, 50, -30, -50]}
)
df_mask = pd.DataFrame(
    {"AAA": [True] * 4, "BBB": [False] * 4, "CCC": [True, False] * 2}
)
df.where(df_mask, -1000)
df.loc[(df.CCC - 6).abs().argsort()[:3]]

AAA  BBB  CCC
2    6   30  -30
1    5   20   50
3    7   40  -50